export const GET_LOGIN_REQUEST = 'GET_LOGIN_REQUEST';
export const GET_LOGIN_SUCCESS = 'GET_LOGIN_SUCCESS';
export const GET_LOGIN_FAILURE = 'GET_LOGIN_FAILURE';

export const USER_LOGOUT_REQUEST= 'USER_LOGOUT_REQUEST';

export const GET_CLAIMS_REQUESTED = 'GET_CLAIMS_REQUESTED';
export const GET_CLAIMS_SUCCESS = 'GET_CLAIMS_SUCCESS';
export const GET_CLAIMS_FAILURE = 'GET_CLAIMS_FAILURE';
export const UPDATE_FAIL_CLIAM = "UPDATE_FAIL_CLIAM";
export const SAVE_CLAIM_CATEGORIES = "SAVE_CLAIM_CATEGORIES";
export const UPDATE_CLAIM_CATEGORY = "UPDATE_CLAIM_CATEGORY";
export const SELECT_CLAIM_BY_CLAIMS = "SELECT_CLAIM_BY_CLAIMS";

export const SELECT_CLAIM = "SELECT_CLAIM";
export const CLEAR_SELECTED_CLAIM= "CLEAR_SELECTED_CLAIM";
export const CLEAR_REDUCER = "CLEAR_REDUCER";
export const SAVE_ACTION_DATA = "SAVE_ACTION_DATA";
export const UPDATE_SELECTED_CLAIM="UPDATE_SELECTED_CLAIM";
export const GET_CLAIM_DETAIL = "GET_CLAIM_DETAIL";
export const UPDATE_CLAIM_DETAIL = "UPDATE_CLAIM_DETAIL";
export const UPDATE_CLAIM_LOCKED = "UPDATE_CLAIM_LOCKED";

export const GET_CATEGORIES_SUBCATEGORIES = "GET_CATEGORIES_SUBCATEGORIES";
export const UPDATE_CATEGORIES_SUBCATEGORIES = "UPDATE_CATEGORIES_SUBCATEGORIES";
export const FAIL_CATEGORIES_SUBCATEGORIES = "FAIL_CATEGORIES_SUBCATEGORIES";
export const UPDATE_EXAMINER_AUDITOR_NAME = "UPDATE_EXAMINER_AUDITOR_NAME";
export const ADD_SUBCAT = "ADD_SUBCAT";
export const UPDATE_SUB_CAT = "UPDATE_SUB_CAT";
export const UPDATE_SUBCAT_START = "UPDATE_SUBCAT_START";
export const ADD_SUBCAT_START = "ADD_SUBCAT_START";
export const DELETE_START_CAT = 'DELETE_START_SUBCAT';
export const DELETE_SUBCAT_SUCCESS = 'DELETE_SUBCAT_SUCCESS';
export const CLEAR_MASTER_REDUCER = "CLEAR_MASTER_REDUCER";

export const GET_AUDIT_REPORT_REQUEST = 'GET_AUDIT_REPORT_REQUEST';
export const GET_AUDIT_REPORT_SUCCESS = 'GET_AUDIT_REPORT_SUCCESS';
export const GET_AUDIT_REPORT_FAILURE = 'GET_AUDIT_REPORT_FAILURE';
export const CLEAR_AUDIT_REPORT_DETAILS = 'CLEAR_AUDIT_REPORT_DETAILS';
export const GET_ASSIGNEE_CLAIMS_REQUESTED = 'GET_ASSIGNEE_CLAIMS_REQUESTED';
export const GET_CLAIMS_SUCCESS_BY_FILTER = 'GET_CLAIMS_SUCCESS_BY_FILTER';
export const CLEAR_ALL_CLAIMS = 'CLEAR_ALL_CLAIMS';
export const UPDATE_ERROR_MESSAGE = 'UPDATE_ERROR_MESSAGE';