
export const API_DIRECTORY = { DOC_ROOT: '' };

export const urlConstants = {
  OLD_BASE_URL: process.env.REACT_APP_OLD_ENV_URL,
  BASE_URL: process.env.REACT_APP_ENV_URL,
  BASE_URL_ACTIVATION: process.env.REACT_APP_ENV_URL_ACTIVATION,
  FAKE_URL: 'http://localhost:3000',
  CUSTOM_URL:process.env.REACT_APP_CUSTOM_URL,
};

export const API_INTERFACE = {
  LOGIN: '',
  SEARCH_PLAN_MEMBER:'/searchmember',
  GET_PLAN_UUID:'/getplans',
  // FIND_MEMBER: '/findMember',
  GET_MEMBER: '/getMember',
  FIND_MEMBER_BY_CRITERIA: '/getTargettedMemberByCriteria',
  // GET_MEMBER_PROFILE: '/selectMember',
  GET_MEMBER_PROFILE: '/getSelectMember',
  GET_DEPENDENT_LIST: '/getFamilyMembers',
  GET_MEMBER_ACTIVATION: '/getActivation',
  GET_MEMBER_CARE: '/getCare',
  // GET_MEMBER_MESSAGE: '/getMessages',
  GET_MEMBER_MESSAGE: '/getMessages',
  REPLY_MESSAGE: '/replyMessage',
  GET_ALL_TEMPLATES: '/getTemplate',
  CREATE_TEMPLATE: '/templates',
  CREATE_MESSAGE: '/createMessages',
  // GET_ALL_MESSAGES: '/getMessages',
  MEMBER_SEARCH_BY_FAMILYID: '/findMember',
  UNSUBSCRIBE_LINK: '/unsubscribeUrl',
  GET_TEMP_MEMBER_PORTAL_LOGIN: '/updateMemberStatus',
  DELETE_CSR_MEMBER_PORTAL_SESSION: '/deleteUser',
  GET_MEMBER_INBOX_MESSAGE: '/getMemberMessages',
  GET_REFERRALS: '/getReferrals',
  UPDATE_MEMBER_DETAILS: '/updateMemberUserData',
  UPDATE_ADDRESS: '/updateAddress',
  // SEARCH_PCP: '/searchPcp',
  SEARCH_PCP: '/getPcps',
  UPDATE_PCP: '/updatePcp',
  ACCESS_APPROVAL: '/updateAccessApproval',
  RESET_ACCOUNT: '/resetAccount',
  SUBMIT_REFERRAL: '/submitReferral',
  // RETRIEVE_REPLY_MESSAGE: '/retrieveReplyMessage',
  RETRIEVE_REPLY_MESSAGE: '/getReplyMessages',
  GET_RESOURCES: '/getResources',
  GET_SPECIALTIES: '/getSpecialties',
  UPDATE_MESSAGES: '/updateMessages',
  FIND_MASTER_PLANS: '/findMasterPlans',
  CREATE_IN_APP_MESSAGE: '/createInAppMessage',
  VERIFY_ELIGIBILITY: '/verifyEligibility',
  CHECK_USERNAME: '/checkUserName',
  CREATE_USER: '/createUser',
  GET_MEMBERS_DATA: '/getMembersDataByEmployeeCertificateNumber'
};

export const uriConstants = {
  CLAIM_SEARCH_URL: "/claims",
  CLAIM_DETAIL: "/claimDetail",
  CLAIM_ACTION: "/claimAction",
  CREATE_USER_URL: "/createuser",
  SEND_CODE: "/sendaccesscode",
  VERIFY_CODE: "/verifyaccesscode",
  RESET_PWD: "/resetpassword",
  GET_CURRENT_CLAIM_STATUS: "/GetConcurrentUpdateFlag",
  CHECK_CLAIM_LOCKED: "/GetConcurrentUpdateFlag",
  VERIFY_USER_EMAIL: "/verifyuseremail",
  GET_USER: "/GetUsers",
  GET_CONFIG: "/config",
  GET_CATEGORIES_SUBCATEGORIES: "/masterCategories",
  UPDATE_CLAIM_CATEGORIES: "/claimCategories",
  GET_AUDIT_CLAIM_REPORT: "/reports",
  ADD_UPDATE_SUBCAT: "/saveMasterCategory",
  UPDATE_MASTER_SUBCAT : "/masterCategory",
  DELETE_MASTER_SUBCAT : "/deleteMasterCategory",
  GET_CLAIMS_BY_ASSIGNEE: '/assignedClaims',
  GET_CLAIMS_BY_STATUS: '/claimsWithStatus',
};

